version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: eslint-plugin-vue
    versions:
    - 7.5.0
    - 7.6.0
    - 7.7.0
    - 7.8.0
  - dependency-name: stylelint
    versions:
    - 13.10.0
    - 13.11.0
    - 13.12.0
    - 13.9.0
  - dependency-name: sass-loader
    versions:
    - 10.1.1
    - 11.0.0
  - dependency-name: "@vue/cli-service"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-eslint"
    versions:
    - 4.5.11
  - dependency-name: "@vue/cli-plugin-babel"
    versions:
    - 4.5.11
