approvedGitRepositories:
  - "**"

enableScripts: true

nodeLinker: node-modules

npmScopes:
  get-uncommon:
    npmAlwaysAuth: true
    npmAuthToken: "${NODE_AUTH_TOKEN:-}"
    npmRegistryServer: "https://npm.pkg.github.com"
